[package]
name = "advent"
version = "0.15.0"
edition = "2018"

[dependencies]
md5 = "0.6.1"
regex = "1"
maplit = "1"
pcre = "0.2.3"
text_io = "0.1.7"
itertools = "0.8.0"
num-traits = "0.2.6"
serde_json = "1"
simple-error = "0.1.13"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3
